{
 "title": "Main dashboard",
 "time": { "from": "2024-01-15T14:30:22.000Z", "to": "2024-01-29T09:14:35.000Z" },
 "templating": {
  "list": [
   {
    "name": "product",
    "label": "product",
    "query": "SELECT DISTINCT arrayJoin(tags) FROM Reviews.processed_data\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Общая активность",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Все отзывы",
     "type": "timeseries",
     "description": "Показывает активность получения отзывов всех типов",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n    toDate(date) AS day,\n    COUNT(*) AS \"Отзывы в день\"\nFROM Reviews.processed_data\nGROUP BY day\nORDER BY day"
      }
     ]
    },
    {
     "title": "Отчетность по тегам",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 331 },
     "targets": [
      {
       "rawSql": "SELECT\n    arrayJoin(tags) AS \"Продукт\",\n    COUNT(*) AS \"Количество отзывов\",\n    sum(sentiment = 0) AS \"Негативные отзывы\",\n    100 * sum(sentiment = 0) / COUNT(*) AS \"Процент негативных\",\n    sum(sentiment = 1) AS \"Нейтральные отзывы\",\n    100 * sum(sentiment = 1) / COUNT(*) AS \"Процент нейтральных\",\n    sum(sentiment = 2) AS \"Позитивные отзывы\",\n    100 * sum(sentiment = 2) / COUNT(*) AS \"Процент позитивных\"\nFROM Reviews.processed_data\nGROUP BY \"Продукт\"\nORDER BY \"Количество отзывов\" DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Абсолютное число отзывов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Все отзывы",
     "type": "gauge",
     "description": "Показывает общее количество отзывов на наши продукты",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nCOUNT(*) AS negative_count\nFROM Reviews.processed_data\n"
      }
     ]
    },
    {
     "title": "Положительные отзывы",
     "type": "gauge",
     "description": "Показывает общее количество положительных отзывов на наши продукты",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nCOUNT(*) AS negative_count\nFROM Reviews.processed_data\nWHERE sentiment = 2"
      }
     ]
    },
    {
     "title": "Нейтральные отзывы",
     "type": "gauge",
     "description": "Показывает общее количество нейтральных отзывов на наши продукты",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nCOUNT(*) AS negative_count\nFROM Reviews.processed_data\nWHERE sentiment = 1"
      }
     ]
    },
    {
     "title": "Негативные отзывы",
     "type": "gauge",
     "description": "Показывает общее количество негативных отзывов на наши продукты",
     "gridPos": { "h": 5, "w": 5, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\nCOUNT(*) AS negative_count\nFROM Reviews.processed_data\nWHERE sentiment = 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Настроение пользователей",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Настроение пользователей",
     "type": "timeseries",
     "description": "Описывает динамику отзывов в разбитии по настроению",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n    toDate(date) AS \"Дата\",\n    sum(sentiment = 0) AS \"Негативные отзывы\",\n    sum(sentiment = 1) AS \"Нейтральные отзывы\",\n    sum(sentiment = 2) AS \"Позитивные отзывы\"\nFROM Reviews.processed_data\nGROUP BY \"Дата\"\nORDER BY \"Дата\""
      }
     ]
    },
    {
     "title": "Соотношения отзывов",
     "type": "piechart",
     "description": "Показывает суммарное общее соотношение отзывов ",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 336 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n    sum(sentiment = 0) AS \"Негативные отзывы\",\n    sum(sentiment = 1) AS \"Нейтральные отзывы\",\n    sum(sentiment = 2) AS \"Положительные отзывы\"\nFROM Reviews.processed_data\n"
      }
     ]
    },
    {
     "title": "Соотношения отзывов",
     "type": "bargauge",
     "description": "Показывает суммарное общее соотношение отзывов в виде бачарта",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 336 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n    sum(sentiment = 0) AS \"Негативные отзывы\",\n    sum(sentiment = 1) AS \"Нейтральные отзывы\",\n    sum(sentiment = 2) AS \"Позитивные отзывы\"\nFROM Reviews.processed_data\n"
      }
     ]
    },
    {
     "title": "Негативное настроение пользователей",
     "type": "timeseries",
     "description": "Описывает динамику негативных отзывов",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 346 },
     "targets": [
      {
       "rawSql": "SELECT\n    sum(sentiment = 0) AS \"Отрицательные отзывы\",\n    toDate(date) AS day\nFROM Reviews.processed_data\nGROUP BY day\nORDER BY day"
      }
     ]
    },
    {
     "title": "Положительное настроение пользователей",
     "type": "timeseries",
     "description": "Описывает динамику положительных отзывов",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 346 },
     "targets": [
      {
       "rawSql": "SELECT\n    sum(sentiment = 2) AS \"Положительные отзывы\",\n    toDate(date) AS day\nFROM Reviews.processed_data\nGROUP BY day\nORDER BY day"
      }
     ]
    },
    {
     "title": "Нейтральное настроение пользователей",
     "type": "timeseries",
     "description": "Описывает динамику нейтральных отзывов",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 357 },
     "targets": [
      {
       "rawSql": "SELECT\n    sum(sentiment = 1) AS \"Нейтральные отзывы\",\n    toDate(date) AS day\nFROM Reviews.processed_data\nGROUP BY day\nORDER BY day"
      }
     ]
    },
    {
     "title": "Текущее настроение пользователей",
     "type": "timeseries",
     "description": "Описывает нормированную динамику настроения пользователей",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 357 },
     "targets": [
      {
       "rawSql": "SELECT\n    toDate(date) AS time,\n    (sum(sentiment = 0) * (-1) + sum(sentiment = 2)) / count(*) AS \"Отношение\"\nFROM Reviews.processed_data\nGROUP BY time\nORDER BY time"
      }
     ]
    },
    {
     "title": "Кумулятивное настроение пользователей",
     "type": "timeseries",
     "description": "Описывает кумулятивную нормированную динамику настроения пользователей",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 370 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n    SELECT\n        toDate(date) AS time,\n        (sum(sentiment = 0) * (-1) + sum(sentiment = 2)) / count(*) AS attitude\n    FROM Reviews.processed_data\n    GROUP BY time\n)\n\nSELECT\n    time,\n    attitude,\n    sum(attitude) OVER (ORDER BY time ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS \"Кумулятивное отношение\"\nFROM daily\nORDER BY time"
      }
     ]
    }
   ]
  },
  { "title": "Отчетность по категориям", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Негативные отзывы по тегам",
   "type": "barchart",
   "description": "Диаграмма для отслеживания самых проблемных продуктов",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    arrayJoin(tags) AS \"Продукт\",\n    COUNT(*) AS \"Негативные отзывы\"\nFROM Reviews.processed_data\nWHERE sentiment = 0\nGROUP BY \"Продукт\"\nORDER BY \"Негативные отзывы\" DESC"
    }
   ]
  },
  {
   "title": "Негативные отзывы по тегам",
   "type": "barchart",
   "description": "Диаграмма для отслеживания самых проблемных продуктов",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    arrayJoin(tags) AS \"Продукт\",\n    COUNT(*) AS \"Позитивные отзывы\"\nFROM Reviews.processed_data\nWHERE sentiment = 2\nGROUP BY \"Продукт\"\nORDER BY \"Позитивные отзывы\" DESC"
    }
   ]
  },
  {
   "title": "Отзывы по категориям",
   "type": "timeseries",
   "description": "Покаывает суммарное кол-во отзывов во времени по выбранным категориям",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n    date,\n    arrayJoin(tags) AS product,\n    count(*) AS \"отзывы\"\nFROM Reviews.processed_data\nGROUP BY date, product\nORDER BY date, product"
    }
   ]
  },
  {
   "title": "Отзывы по категориям",
   "type": "timeseries",
   "description": "Покаывает суммарное кол-во отзывов во времени по выбранным категориям",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n    date,\n    concat(arrayJoin(tags), ': ', \n        CASE\n            WHEN sentiment = 0 THEN 'negative'\n            WHEN sentiment = 1 THEN 'neutral'\n            WHEN sentiment = 2 THEN 'positive'\n        END\n    ) AS series,\n    count(*) AS \"Отзывы\"\nFROM Reviews.processed_data\nGROUP BY date, series\nORDER BY date, series"
    }
   ]
  }
 ]
}