http:
  port: 3001
db:
  name: ""
  user: ""
  password: ""
  port: "9000"
kafka: 
  brokers: ""
  group_ids:
    models_service: "models_service_group"
  topics:
    processed_data: "processed_data"
